# Generated by Django 6.0 on 2026-01-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
